language: ruby
rvm:
  - 3.1
  - 3.2
before_install:
  - gem install bundler
script:
  - bundle exec rake
  - bundle exec rspec
cache: bundler

env:
  global:
    - CC_TEST_REPORTER_ID=1be085a9ec82a66481a864aa297f9978f1a2dd6e

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
